theme = "jetbrains_dark"

[editor]
line-number = "relative"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
o = ["open_below", "normal_mode"] # "o", "o<Esc>"
O = ["open_above", "normal_mode"] # "O", "O<Esc>"

[keys.insert]
j = {"k"= "normal_mode"}
