[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true
language-servers = ["rust-analyzer"]

[language-server.rust-analyzer]
command = "rust-analyzer"
# path = "/home/juan/.cargo/bin"
enable_semantic_tokens = true

[language-server.rust-analyzer.config]
check.command = "clippy"

[language-server.rust-analyzer.cargo]
features = "all"

[[language]]
name = "typescript"
roots = ["deno.json", "deno.jsonc", "package.json"]
file-types = ["ts", "tsx"]
auto-format = true
language-servers = ["deno-lsp"]

[[language]]
name = "javascript"
roots = ["deno.json", "deno.jsonc", "package.json"]
file-types = ["js", "jsx"]
auto-format = true
language-servers = ["deno-lsp"]

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
config.deno.enable = true

[[language]]
name = "markdown"
auto-format = true
file-types = ["md"]
language-servers = ["marksman"]

[language-server.marksman]
command = "marksman"
args = ["server"]

[[language]]
name = "cpp"
scope = "source.cpp"
injection-regex = "cpp"
file-types = ["cpp", "cc", "cxx", "hpp", "h", "hxx"]
roots = ["CMakeLists.txt", "compile_commands.json", ".clangd"]
auto-format = true
language-servers = ["clangd"]

[[language]]
name = "c"
scope = "source.c"
injection-regex = "c"
file-types = ["h", "c"]
roots = ["CMakeLists.txt", "compile_commands.json", ".clangd"]
auto-format = true
language-servers = ["clangd"]

[language-server.clangd]
command = "clangd"
args = ["--background-index", "--clang-tidy"]

[[language]]
name = "zig"
scope = "source.zig"
injection-regex = "zig"
file-types = ["zig"]
roots = ["build.zig", "build.zig.zon"]
auto-format = true
language-servers = ["zls"]

[language-server.zls]
command = "zls"
enable_semantic_tokens = true

[[language]]
name = "go"
scope = "source.go"
injection-regex = "go"
file-types = ["go"]
roots = ["go.mod", "go.sum"]
auto-format = true
language-servers = ["gopls"]

[language-server.gopls]
command = "gopls"
enable_semantic_tokens = true

[language-server.superhtml-lsp]
command = "superhtml"
args = ["lsp"]

[[language]]
name = "html"
scope = "source.html"
roots = []
file-types = ["html"]
language-servers = [ "superhtml-lsp" ]
